[application]
sub_package = "fro"
asset_dir = "frontend/fro/public"
out_dir = "frontend/fro/dist"

[web.app]
title = "fro"

[web.watcher]
watch_path = ["frontend/fro/src", "frontend/fro/public", "frontend/fro/assets"]
reload_html = true
index_on_404 = true

[web.resource]
style = []
script = []

[web.resource.dev]
style = []
script = []
