global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'ag-backend'
    metrics_path: /monitoring/metrics
    static_configs:
      - targets: ['host.docker.internal:3010']
        labels:
          service: ag
          env: dev

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
