[application]

[web.app]
title = "fro"

[web.resource]
style = []
script = []

[web.resource.dev]
script = []

[[web.resource.dev.files]]
source = "public"
target = "/"

[web.watcher]
watch_path = ["src", "public", "assets"]
reload_html = true
index_on_404 = true
interval = 1000

[web.server]
ip = "127.0.0.1"
port = 1789
https = false