[application]

[web.app]
title = "fro"

[web.resource]
style = []
script = []

[web.resource.dev]
script = []

[[web.resource.dev.files]]
source = "public"
target = "/"

[web.watcher]
watch_path = ["src", "public"]